### ISSUE TITLE
Mixed Content in Google Maps for Markers

### ISSUE THREAD

**Issue by jamfx** [PhocaCz/PhocaMaps#5]
If you use Google Maps with the "red Pin" as a Marker, this Marker is loaded via HTTP and not HTTPS.
"http://maps.google.com/mapfiles/ms/icons/red-pushpin.png"

So this must be changed to https to use SSL-encrypted connection to Google. I am guessing, this happenes to other Markers, too.

Thanks Jan, for this wonderful update!
Best wishes
JamFX
nik-o-mat.de

**Comment by PhocaCz** [comment]
Hi, thank you for the info, I will change it in the next release.

For now you can go to Icon edit and change the http to https there.

![Icon](https://i.imgur.com/mblTD8k.png)

Thank you, Jan

**Comment by jamfx** [comment]
Thanks! Done! Case closed for me.

**Comment by justinWhite14** [comment]
Anyone who runs into this and doesn't want to update PhocaMaps, you can simply remove http: from the url like this:
//maps.google.com/mapfiles/ms/icons/red-pushpin.png
Then it will automatically be correct for both http and https pages.
