### ISSUE TITLE
Colors for Tracks (OSM) - does not have any effect

### ISSUE THREAD

**Issue by TimmiORG** [PhocaCz/PhocaMaps#9]
Hi there,

please note that it looks like that color inside the KML or the colors specified inside the "colors for Tracks (OSM)" do not have any effect.
All the tracks are always blue.

Let me know if you need sample KML files.

Thank you for the great plugin.

**Comment by PhocaCz** [comment]
Hi, the KML is managed by OSM. so maybe this is more a question on OSM API :idea:

Jan

**Comment by TimmiORG** [comment]
Hi @PhocaCz ,

I was trying to use the following feature:
![grafik](https://github.com/PhocaCz/PhocaMaps/assets/979342/4d84414b-6a27-4b25-874a-c0b0fbd96449)

I have a KML file with different tracks and colors.
Maybe this helps:
https://osm.quelltextlich.at/viewer-js.html?kml_url=https://www.timmi.org/phocamapskml/2019.kml
So it would be already enough if the colors are taken from the KML
This is how the plugin is showing the same KML file:
https://www.timmi.org/index.php/daenemark-und-schweden-tour-2019-bericht-ist-online

**Comment by PhocaCz** [comment]
Hi, I now fully understand. Unfortunately, the colors do not work with KML files only with GPX files. Try to test it with GPX instead.

**Comment by TimmiORG** [comment]
Hi @PhocaCz 

OK understood. I can confirm that it is working with GPX. Maybe this should be mentioned on on the entry in the admin component that this feature is only working with GPX.

Feel free to close this one.

**Comment by PhocaCz** [comment]
Hi, thank you for the info, yes, I will write it to parameter documentation.
